### PR TITLE
Removes boringssl workaround by updating to latest gRPC

### PR DESCRIPTION
**Pull request by adriancole**
Tested manually as well as unit tests. Removing the workaround allows this to work against a stock zipkin-server build.

See https://github.com/GoogleCloudPlatform/stackdriver-zipkin/pull/19#issuecomment-325263640

### CODE REVIEW

**Comment by denyska** [comment]
@adriancole have you tested it on both mac and linux ?

**Comment by adriancole** [comment]
I will build a docker image (to test linux) and get back to you

**Comment by adriancole** [comment]
done!

```bash
± |latest-grpc ✓| → docker run -v $HOME/Downloads:/opt/gcloud -e GOOGLE_APPLICATION_CREDENTIALS="/opt/gcloud/zipkin-demo-81ff9558b5aa.json" -e PROJECT_ID="zipkin-demo" -p 9411:9411 986ff40211a7
                                    ********
                                  **        **
                                 *            *
                                **            **
                                **            **
                                 **          **
                                  **        **
                                    ********
                                      ****
                                      ****
        ****                          ****
     ******                           ****                                 ***
  ****************************************************************************
    *******                           ****                                 ***
        ****                          ****
                                       **
                                       **


             *****      **     *****     ** **       **     **   **
               **       **     **  *     ***         **     **** **
              **        **     *****     ****        **     **  ***
             ******     **     **        **  **      **     **   **

:: Powered by Spring Boot ::         (v1.5.6.RELEASE)

2017-08-29 01:26:32.510  INFO 5 --- [           main] c.g.c.t.z.StackdriverZipkinCollector     : Starting StackdriverZipkinCollector on 29329ebfa1e2 with PID 5 (/usr/src/app/collector/target/collector-0.4.0-SNAPSHOT.jar started by root in /usr/src/app)
2017-08-29 01:26:32.524  INFO 5 --- [           main] c.g.c.t.z.StackdriverZipkinCollector     : The following profiles are active: shared
2017-08-29 01:26:32.671  INFO 5 --- [           main] ationConfigEmbeddedWebApplicationContext : Refreshing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@53ca01a2: startup date [Tue Aug 29 01:26:32 UTC 2017]; root of context hierarchy
2017-08-29 01:26:35.679  INFO 5 --- [           main] org.eclipse.jetty.util.log               : Logging initialized @5057ms to org.eclipse.jetty.util.log.Slf4jLog
2017-08-29 01:26:35.880  INFO 5 --- [           main] e.j.JettyEmbeddedServletContainerFactory : Server initialized with port: 9411
2017-08-29 01:26:35.884  INFO 5 --- [           main] org.eclipse.jetty.server.Server          : jetty-9.4.6.v20170531
2017-08-29 01:26:36.072  INFO 5 --- [           main] org.eclipse.jetty.server.session         : DefaultSessionIdManager workerName=node0
2017-08-29 01:26:36.077  INFO 5 --- [           main] org.eclipse.jetty.server.session         : No SessionScavenger set, using defaults
2017-08-29 01:26:36.079  INFO 5 --- [           main] org.eclipse.jetty.server.session         : Scavenging every 660000ms
2017-08-29 01:26:36.089  INFO 5 --- [           main] o.e.j.s.h.ContextHandler.application     : Initializing Spring embedded WebApplicationContext
2017-08-29 01:26:36.090  INFO 5 --- [           main] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 3421 ms
2017-08-29 01:26:36.503  INFO 5 --- [           main] o.s.b.w.servlet.ServletRegistrationBean  : Mapping servlet: 'dispatcherServlet' to [/]
2017-08-29 01:26:36.504  INFO 5 --- [           main] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'metricsFilter' to: [/*]
2017-08-29 01:26:36.505  INFO 5 --- [           main] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'characterEncodingFilter' to: [/*]
2017-08-29 01:26:36.505  INFO 5 --- [           main] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'hiddenHttpMethodFilter' to: [/*]
2017-08-29 01:26:36.505  INFO 5 --- [           main] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'httpPutFormContentFilter' to: [/*]
2017-08-29 01:26:36.505  INFO 5 --- [           main] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'requestContextFilter' to: [/*]
2017-08-29 01:26:36.505  INFO 5 --- [           main] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'webRequestLoggingFilter' to: [/*]
2017-08-29 01:26:36.505  INFO 5 --- [           main] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'applicationContextIdFilter' to: [/*]
2017-08-29 01:26:36.509  INFO 5 --- [           main] o.e.jetty.server.handler.ContextHandler  : Started o.s.b.c.e.j.JettyEmbeddedWebAppContext@17fc391b{/,[file:///tmp/jetty-docbase.3556968158810903093.9411/],AVAILABLE}
2017-08-29 01:26:36.509  INFO 5 --- [           main] org.eclipse.jetty.server.Server          : Started @5888ms
2017-08-29 01:26:36.719  INFO 5 --- [           main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 
2017-08-29 01:26:36.720  INFO 5 --- [           main] ipkinStackdriverStorageAutoConfiguration : Configured Executor for ZipkinStackDriver Storage with: Executor(corePoolSize=1, maxPoolSize=5, queueCapacity=200000)
2017-08-29 01:26:36.749  INFO 5 --- [           main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService  'stackdriverExecutor'
2017-08-29 01:26:38.519  INFO 5 --- [           main] s.w.s.m.m.a.RequestMappingHandlerAdapter : Looking for @ControllerAdvice: org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@53ca01a2: startup date [Tue Aug 29 01:26:32 UTC 2017]; root of context hierarchy
2017-08-29 01:26:38.644  INFO 5 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/api/v2/spans],methods=[POST]}" onto public org.springframework.util.concurrent.ListenableFuture<org.springframework.http.ResponseEntity<?>> zipkin.server.ZipkinHttpCollector.uploadSpansJson2(java.lang.String,byte[])
2017-08-29 01:26:38.646  INFO 5 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/api/v1/spans],methods=[POST]}" onto public org.springframework.util.concurrent.ListenableFuture<org.springframework.http.ResponseEntity<?>> zipkin.server.ZipkinHttpCollector.uploadSpansJson(java.lang.String,byte[])
2017-08-29 01:26:38.647  INFO 5 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/api/v1/spans],methods=[POST],consumes=[application/x-thrift]}" onto public org.springframework.util.concurrent.ListenableFuture<org.springframework.http.ResponseEntity<?>> zipkin.server.ZipkinHttpCollector.uploadSpansThrift(java.lang.String,byte[])
2017-08-29 01:26:38.659  INFO 5 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/error],produces=[text/html]}" onto public org.springframework.web.servlet.ModelAndView org.springframework.boot.autoconfigure.web.BasicErrorController.errorHtml(javax.servlet.http.HttpServletRequest,javax.servlet.http.HttpServletResponse)
2017-08-29 01:26:38.659  INFO 5 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/error]}" onto public org.springframework.http.ResponseEntity<java.util.Map<java.lang.String, java.lang.Object>> org.springframework.boot.autoconfigure.web.BasicErrorController.error(javax.servlet.http.HttpServletRequest)
2017-08-29 01:26:38.716  INFO 5 --- [           main] o.s.w.s.handler.SimpleUrlHandlerMapping  : Mapped URL path [/webjars/**] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2017-08-29 01:26:38.716  INFO 5 --- [           main] o.s.w.s.handler.SimpleUrlHandlerMapping  : Mapped URL path [/**] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2017-08-29 01:26:39.381  INFO 5 --- [           main] o.s.b.a.e.mvc.EndpointHandlerMapping     : Mapped "{[/configprops || /configprops.json],methods=[GET],produces=[application/vnd.spring-boot.actuator.v1+json || application/json]}" onto public java.lang.Object org.springframework.boot.actuate.endpoint.mvc.EndpointMvcAdapter.invoke()
2017-08-29 01:26:39.383  INFO 5 --- [           main] o.s.b.a.e.mvc.EndpointHandlerMapping     : Mapped "{[/loggers/{name:.*}],methods=[GET],produces=[application/vnd.spring-boot.actuator.v1+json || application/json]}" onto public java.lang.Object org.springframework.boot.actuate.endpoint.mvc.LoggersMvcEndpoint.get(java.lang.String)
2017-08-29 01:26:39.384  INFO 5 --- [           main] o.s.b.a.e.mvc.EndpointHandlerMapping     : Mapped "{[/loggers/{name:.*}],methods=[POST],consumes=[application/vnd.spring-boot.actuator.v1+json || application/json],produces=[application/vnd.spring-boot.actuator.v1+json || application/json]}" onto public java.lang.Object org.springframework.boot.actuate.endpoint.mvc.LoggersMvcEndpoint.set(java.lang.String,java.util.Map<java.lang.String, java.lang.String>)
2017-08-29 01:26:39.384  INFO 5 --- [           main] o.s.b.a.e.mvc.EndpointHandlerMapping     : Mapped "{[/loggers || /loggers.json],methods=[GET],produces=[application/vnd.spring-boot.actuator.v1+json || application/json]}" onto public java.lang.Object org.springframework.boot.actuate.endpoint.mvc.EndpointMvcAdapter.invoke()
2017-08-29 01:26:39.385  INFO 5 --- [           main] o.s.b.a.e.mvc.EndpointHandlerMapping     : Mapped "{[/health || /health.json],methods=[GET],produces=[application/vnd.spring-boot.actuator.v1+json || application/json]}" onto public java.lang.Object org.springframework.boot.actuate.endpoint.mvc.HealthMvcEndpoint.invoke(javax.servlet.http.HttpServletRequest,java.security.Principal)
2017-08-29 01:26:39.387  INFO 5 --- [           main] o.s.b.a.e.mvc.EndpointHandlerMapping     : Mapped "{[/info || /info.json],methods=[GET],produces=[application/vnd.spring-boot.actuator.v1+json || application/json]}" onto public java.lang.Object org.springframework.boot.actuate.endpoint.mvc.EndpointMvcAdapter.invoke()
2017-08-29 01:26:39.390  INFO 5 --- [           main] o.s.b.a.e.mvc.EndpointHandlerMapping     : Mapped "{[/autoconfig || /autoconfig.json],methods=[GET],produces=[application/vnd.spring-boot.actuator.v1+json || application/json]}" onto public java.lang.Object org.springframework.boot.actuate.endpoint.mvc.EndpointMvcAdapter.invoke()
2017-08-29 01:26:39.397  INFO 5 --- [           main] o.s.b.a.e.mvc.EndpointHandlerMapping     : Mapped "{[/metrics/{name:.*}],methods=[GET],produces=[application/vnd.spring-boot.actuator.v1+json || application/json]}" onto public java.lang.Object org.springframework.boot.actuate.endpoint.mvc.MetricsMvcEndpoint.value(java.lang.String)
2017-08-29 01:26:39.398  INFO 5 --- [           main] o.s.b.a.e.mvc.EndpointHandlerMapping     : Mapped "{[/metrics || /metrics.json],methods=[GET],produces=[application/vnd.spring-boot.actuator.v1+json || application/json]}" onto public java.lang.Object org.springframework.boot.actuate.endpoint.mvc.EndpointMvcAdapter.invoke()
2017-08-29 01:26:39.398  INFO 5 --- [           main] o.s.b.a.e.mvc.EndpointHandlerMapping     : Mapped "{[/dump || /dump.json],methods=[GET],produces=[application/vnd.spring-boot.actuator.v1+json || application/json]}" onto public java.lang.Object org.springframework.boot.actuate.endpoint.mvc.EndpointMvcAdapter.invoke()
2017-08-29 01:26:39.399  INFO 5 --- [           main] o.s.b.a.e.mvc.EndpointHandlerMapping     : Mapped "{[/trace || /trace.json],methods=[GET],produces=[application/vnd.spring-boot.actuator.v1+json || application/json]}" onto public java.lang.Object org.springframework.boot.actuate.endpoint.mvc.EndpointMvcAdapter.invoke()
2017-08-29 01:26:39.401  INFO 5 --- [           main] o.s.b.a.e.mvc.EndpointHandlerMapping     : Mapped "{[/heapdump || /heapdump.json],methods=[GET],produces=[application/octet-stream]}" onto public void org.springframework.boot.actuate.endpoint.mvc.HeapdumpMvcEndpoint.invoke(boolean,javax.servlet.http.HttpServletRequest,javax.servlet.http.HttpServletResponse) throws java.io.IOException,javax.servlet.ServletException
2017-08-29 01:26:39.405  INFO 5 --- [           main] o.s.b.a.e.mvc.EndpointHandlerMapping     : Mapped "{[/auditevents || /auditevents.json],methods=[GET],produces=[application/vnd.spring-boot.actuator.v1+json || application/json]}" onto public org.springframework.http.ResponseEntity<?> org.springframework.boot.actuate.endpoint.mvc.AuditEventsMvcEndpoint.findByPrincipalAndAfterAndType(java.lang.String,java.util.Date,java.lang.String)
2017-08-29 01:26:39.405  INFO 5 --- [           main] o.s.b.a.e.mvc.EndpointHandlerMapping     : Mapped "{[/env/{name:.*}],methods=[GET],produces=[application/vnd.spring-boot.actuator.v1+json || application/json]}" onto public java.lang.Object org.springframework.boot.actuate.endpoint.mvc.EnvironmentMvcEndpoint.value(java.lang.String)
2017-08-29 01:26:39.406  INFO 5 --- [           main] o.s.b.a.e.mvc.EndpointHandlerMapping     : Mapped "{[/env || /env.json],methods=[GET],produces=[application/vnd.spring-boot.actuator.v1+json || application/json]}" onto public java.lang.Object org.springframework.boot.actuate.endpoint.mvc.EndpointMvcAdapter.invoke()
2017-08-29 01:26:39.406  INFO 5 --- [           main] o.s.b.a.e.mvc.EndpointHandlerMapping     : Mapped "{[/beans || /beans.json],methods=[GET],produces=[application/vnd.spring-boot.actuator.v1+json || application/json]}" onto public java.lang.Object org.springframework.boot.actuate.endpoint.mvc.EndpointMvcAdapter.invoke()
2017-08-29 01:26:39.407  INFO 5 --- [           main] o.s.b.a.e.mvc.EndpointHandlerMapping     : Mapped "{[/mappings || /mappings.json],methods=[GET],produces=[application/vnd.spring-boot.actuator.v1+json || application/json]}" onto public java.lang.Object org.springframework.boot.actuate.endpoint.mvc.EndpointMvcAdapter.invoke()
2017-08-29 01:26:39.598  INFO 5 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Registering beans for JMX exposure on startup
2017-08-29 01:26:39.617  INFO 5 --- [           main] o.s.c.support.DefaultLifecycleProcessor  : Starting beans in phase 0
2017-08-29 01:26:39.761  INFO 5 --- [           main] o.e.j.s.h.ContextHandler.application     : Initializing Spring FrameworkServlet 'dispatcherServlet'
2017-08-29 01:26:39.767  INFO 5 --- [           main] o.s.web.servlet.DispatcherServlet        : FrameworkServlet 'dispatcherServlet': initialization started
2017-08-29 01:26:39.790  INFO 5 --- [           main] o.s.web.servlet.DispatcherServlet        : FrameworkServlet 'dispatcherServlet': initialization completed in 23 ms
2017-08-29 01:26:39.831  INFO 5 --- [           main] o.e.jetty.server.AbstractConnector       : Started ServerConnector@2b30a42c{HTTP/1.1,[http/1.1]}{0.0.0.0:9411}
2017-08-29 01:26:39.833  INFO 5 --- [           main] .s.b.c.e.j.JettyEmbeddedServletContainer : Jetty started on port(s) 9411 (http/1.1)
2017-08-29 01:26:39.837  INFO 5 --- [           main] c.g.c.t.z.StackdriverZipkinCollector     : Started StackdriverZipkinCollector in 8.513 seconds (JVM running for 9.215)
```

```bash
$ curl -s 192.168.99.100:9411/api/v2/spans -H'Content-Type: application/json' -d'[{
>   "traceId": "86154a4ba6e91388",
>   "id": "86154a4ba6e91387",
>   "kind": "SERVER",
>   "name": "get",
>   "timestamp": 1503970062123456,
>   "duration": 207000,
>   "localEndpoint": {
>     "serviceName": "testservice",
>     "ipv4": "113.210.108.10"
>   },
>   "tags": {
>     "http.path": "/api/blah"
>   }
> }]'
```

and voilla

screen shot 2017-08-29 at 9 30 40 am

**Comment by bogdandrutu** [comment]
Please rebase the PR.

**Pull request merged**
