### PR TITLE
Added metrics for Stackdriver component

### PR DESCRIPTION
**Pull request by denyska**
That is how metrics mightlook like on http://localhost:9411/metrics

```
   "gauge.zipkin_storage.stackdriver.active_threads":5,
   "gauge.zipkin_storage.stackdriver.pool_size":5,
   "gauge.zipkin_storage.stackdriver.core_pool_size":1,
   "gauge.zipkin_storage.stackdriver.max_pool_size":10,
   "gauge.zipkin_storage.stackdriver.queue_size":20,
   "counter.zipkin_storage.stackdriver.sent":99,
```

### CODE REVIEW

**Comment by adriancole** [comment]
Mostly on holiday so wont be able to review till tomorrow or next but dont
block on me

**Comment by kevinmdavis** [comment]
+ @bogdandrutu

**Comment by denyska** [comment]
@kevinmdavis @bogdandrutu related PR https://github.com/GoogleCloudPlatform/cloud-trace-java/pull/79 . If we upgrade cloud-trace-java to grpc 1.0.2 and release new version of cloud-trace-java then upgrade stackdriver-zipkin will be much easier.

**Comment by bogdandrutu** [comment]
@denyska Upgrading cloud-trace-java to grpc 1.0.2 and release implies any changes to the current PR?

**Comment by denyska** [comment]
@bogdandrutu  For this PR no. This PR is about new set of metrics.  But https://github.com/GoogleCloudPlatform/stackdriver-zipkin/pull/31 can be simplified. If cloud-trace-java with grpc@1.0.2 already released to Central I can incorporate it in another PR.

**Pull request merged**
